### PR TITLE
Graph attention network

### PR DESCRIPTION
**Pull request by c-yuwei**
This PR integrates several neural network pipelines

1. graph attention network (GAT) for CON WU classification

- [x] GAT Model training
- [x] GAT Model evaluation
- [x] GAT Model visualization
- [x] Documentation
- [x] GUI

2. improve scatter plot for regression

It has been tested with the following MATLAB versions
- [x] R2020b Linux
- [x] R2020b Windows
- [x] R2022a Windows
- [x] R2021a MAC

### CODE REVIEW

**Comment by c-yuwei** [comment]
Please check two m scripts particularly:
1. Format.m
2. tostring.m

**Comment by c-yuwei** [comment]
Test_braph2 in windows 2020b
yuwe_test_02052022

**Comment by annacanal** [comment]
test_NNDataGAT_CON_WU passed in MAC version matlab 2021a.

I will test later the whole test_braph2 (it is very hard to run the whole test since many windows from NN pop up, and then I cannot use the computer for anything since every 5 seconds matlab windows open)

**Comment by annacanal** [comment]
test_braph2 passed on MAC and matlab 2021a

**Comment by c-yuwei** [comment]
This branch is stable and the features (GNN and so on) will be merged in another branch based on updated version

**Pull request closed without merging**
